# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vector_gcd <- function(vec) {
    .Call(`_minMSE_vector_gcd`, vec)
}

count_occurrences <- function(df_treatments, curr_treatment) {
    .Call(`_minMSE_count_occurrences`, df_treatments, curr_treatment)
}

